### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by cBob6** [daveajones/cartulary#15]
I've tried installing 3 times (this last time using defaults as much as possible) and I receive the same error each time.  I've followed the video tutorial exactly, only substituting my unique info. I am not a programer and know just enough basics to be dangerous I suppose, so it very well could be user error on my part. Here is the error on from terminal, any guidance is much appreciated. Thank you!

#####################################################
##---------------------------------------------------
##                                                   
##---------------------------------------------------
#####################################################

PHP Warning:  mysqli::mysqli(): (28000/1045): Access denied for user 'cartulary'@'localhost' (using password: YES) in /opt/cartulary/includes/opml.php on line 1522
PHP Warning:  mysqli::prepare(): Couldn't fetch mysqli in /opt/cartulary/includes/opml.php on line 1532
PHP Warning:  get_all_outlines(): Couldn't fetch mysqli in /opt/cartulary/includes/opml.php on line 1532
PHP Fatal error:  Call to a member function execute() on a non-object in /opt/cartulary/includes/opml.php on line 1533
/opt/cartulary/aggrivate/aggrivate.js:51
    if(err) throw err;
            ^

Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'cartulary'@'localhost' (using password: YES)
    at Handshake.Sequence._packetToError (/opt/cartulary/aggrivate/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Handshake.ErrorPacket (/opt/cartulary/aggrivate/node_modules/mysql/lib/protocol/sequences/Handshake.js:101:18)
    at Protocol._parsePacket (/opt/cartulary/aggrivate/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/opt/cartulary/aggrivate/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/opt/cartulary/aggrivate/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/opt/cartulary/aggrivate/node_modules/mysql/lib/Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (/opt/cartulary/aggrivate/node_modules/mysql/lib/protocol/Protocol.js:135:48)
    at Protocol.handshake (/opt/cartulary/aggrivate/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at Connection.connect (/opt/cartulary/aggrivate/node_modules/mysql/lib/Connection.js:109:18)
    at Object.<anonymous> (/opt/cartulary/aggrivate/aggrivate.js:36:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
/root
PHP Warning:  mysqli::mysqli(): (28000/1045): Access denied for user 'cartulary'@'localhost' (using password: YES) in /opt/cartulary/includes/feeds.php on line 2121
PHP Warning:  mysqli::prepare(): Couldn't fetch mysqli in /opt/cartulary/includes/feeds.php on line 2131
PHP Warning:  get_updated_feeds(): Couldn't fetch mysqli in /opt/cartulary/includes/feeds.php on line 2131
PHP Fatal error:  Call to a member function execute() on a non-object in /opt/cartulary/includes/feeds.php on line 2132
PHP Warning:  mysqli::mysqli(): (28000/1045): Access denied for user 'cartulary'@'localhost' (using password: YES) in /opt/cartulary/includes/auth.php on line 2294
PHP Warning:  mysqli::prepare(): Couldn't fetch mysqli in /opt/cartulary/includes/auth.php on line 2329
PHP Warning:  get_users(): Couldn't fetch mysqli in /opt/cartulary/includes/auth.php on line 2329
PHP Fatal error:  Call to a member function execute() on a non-object in /opt/cartulary/includes/auth.php on line 2330

##-----------------------------------------------------------------------------------

Installation is finished.  Just point your browser at the FQDN you gave above and    
log in with:

At this point it would be a good idea to peruse through the cartulary.conf file and  
make any tweaks you want before using the system in earnest, like setting the
timezone and setting up a more secure password for the cartulary MySQL user.

It would also be a good idea to tweak your php.ini file to allow for larger file     
uploads (for enclosures) and longer script timeouts (for slow feeds).                

A log of the installation is at /tmp/cartinstall.log  Enjoy!

**Comment by cBob6** [comment]
Disregard. User error.
